# Generated by Django 3.2.4 on 2021-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20210629_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'Avançado'), ('I', 'Intermediário'), ('B', 'Básico')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'Noturno'), ('M', 'Matutino'), ('V', 'Vespertino')], default='M', max_length=1),
        ),
    ]
